name: üöÄ Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_NAME: mujer-automotriz

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: üöÄ Deploy
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

    steps:
      - name: Print APP_NAME
        run: echo $APP_NAME

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '50'

      - name: üëÄ Read app name
        uses: SebRollen/toml-action@v1.2.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: üéà Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: ‚öôÔ∏è Install 1password CLI
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: üîë Load environment variables
        id: op_secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          FLY_API_TOKEN: op://mujer-automotriz/FLY/FLY_API_TOKEN
          SENTRY_AUTH_TOKEN: op://mujer-automotriz/SENTRY/SENTRY_AUTH_TOKEN
          RESEND_API_KEY: op://mujer-automotriz/RESEND/RESEND_API_KEY
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: üß∞ Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: üß® Destroy all Fly.io Machines
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          flyctl machines list --json | jq -r '.[].id' | xargs -n1 flyctl machines destroy --force
        env:
          FLY_API_TOKEN: ${{ env.FLY_API_TOKEN }} 
          RESEND_API_KEY: ${{ env.RESEND_API_KEY }}

      - name: üöÄ Deploy Production üöÄ
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          flyctl deploy --remote-only \
          --build-arg COMMIT_SHA=${{ github.sha }} \
          --build-arg OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} \
          --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ env.FLY_API_TOKEN }}
