name: ğŸš€ Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_NAME: mujer-automotriz

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: ğŸš€ Deploy
    runs-on: ubuntu-22.04
    # only build/deploy branches on pushes and PRs
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

    steps:
      - name: Print APP_NAME
        run: echo $APP_NAME

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '50'

      - name: ğŸ‘€ Read app name
        uses: SebRollen/toml-action@v1.2.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: ğŸˆ Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: âš™ï¸ Install 1password CLI
        uses: 1password/load-secrets-action/configure@v2
        with:
          # Persist the 1Password Service Account Authorization token
          # for next steps.
          # Keep in mind that every single step in the job is now able
          # to access the token.
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: ğŸ”‘ Load environment variables
        id: op_secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          FLY_API_TOKEN: op://mujer-automotriz/FLY/FLY_API_TOKEN
          SENTRY_AUTH_TOKEN: op://mujer-automotriz/SENTRY/SENTRY_AUTH_TOKEN

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: ğŸš€ Deploy Production ğŸš€
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          flyctl deploy --remote-only \
          --build-arg COMMIT_SHA=${{ github.sha }} \
          --build-arg OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} \
          --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ env.FLY_API_TOKEN }}
